plugins:
  voting_alert_votes_left:
    default: 10
  voting_enabled:
    default: true
    client: true
  voting_show_who_voted:
    default: true
    client: true
  voting_show_votes_on_profile:
    default: true
    client: true
  voting_show_votes_on_homepage:
    default: false
    client: true
  voting_show_my_votes_on_homepage:
    default: false
    client: true
  voting_show_votes_before:
    default: top
    client: true
    type: enum
    choices:
      - latest
      - new
      - unread
      - unseen
      - top
      - categories
      - read
      - posted
      - bookmarks
  voting_show_my_votes_before:
    default: top
    client: true
    type: enum
    choices:
      - latest
      - new
      - unread
      - unseen
      - top
      - categories
      - read
      - posted
      - bookmarks
  voting_tl0_vote_limit:
    default: 2
  voting_tl1_vote_limit:
    default: 4
  voting_tl2_vote_limit:
    default: 6
  voting_tl3_vote_limit:
    default: 8
  voting_tl4_vote_limit:
    default: 10
